services:
  postgres:
    image: postgres:16-alpine
    container_name: scalegrams_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: scalegrams_db
      POSTGRES_USER: scalegrams_user
      POSTGRES_PASSWORD: scalegrams_password
    ports:
      - "5433:5432"
    volumes:
      - scalegrams_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U scalegrams_user -d scalegrams_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  scalegrams_postgres_data:
