services:
  postgres:
    image: postgres:16-alpine
    container_name: kcal_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: kcal_db
      POSTGRES_USER: kcal_user
      POSTGRES_PASSWORD: kcal_password
    ports:
      - "5433:5432"
    volumes:
      - kcal_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kcal_user -d kcal_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  ceph-rgw:
    image: docker.io/emadalblueshi/lite-ceph-s3-gw:v1.0.0
    container_name: kcal_ceph_rgw
    restart: unless-stopped
    environment:
      ACCESS_KEY: kcal_access_key
      SECRET_KEY: kcal_secret_key
      BUCKET_NAME: kcal-products
    ports:
      - "7480:7480"
      - "7443:7443"
    volumes:
      - kcal_ceph_data:/var/lib/ceph

volumes:
  kcal_postgres_data:
  kcal_ceph_data:
