ALTER TABLE food ADD COLUMN IF NOT EXISTS image_object_key VARCHAR(500);
ALTER TABLE food ADD COLUMN IF NOT EXISTS source VARCHAR(255);
ALTER TABLE food ADD COLUMN IF NOT EXISTS source_id VARCHAR(255);
ALTER TABLE food ADD COLUMN IF NOT EXISTS last_synced_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE food ALTER COLUMN image_url TYPE VARCHAR(500);
